### ISSUE TITLE
Remove deprecated YARP control-board interface methods

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/QA#16]
Several long-time deprecated methods will get deleted with the next YARP release (2.3.70). Some of these include (current [deprecation list](http://www.yarp.it/deprecated.html)):

* `yarp::dev::IPositionControl::setPositionMode()`
* `yarp::dev::IPositionControlRaw::setPositionModeRaw()`
* `yarp::dev::IPositionDirect::setPositionDirectMode()`
* `yarp::dev::IPositionDirectRaw::setPositionDirectModeRaw()`
* `yarp::dev::ITorqueControl::setTorqueMode()`
* `yarp::dev::ITorqueControlRaw::setTorqueModeRaw()`
* `yarp::dev::IVelocityControl::setVelocityMode()`
* `yarp::dev::IVelocityControlRaw::setVelocityModeRaw()`

Said methods were migrated upstream to the `yarp::dev::IControlMode` interface ([docs](http://www.yarp.it/classyarp_1_1dev_1_1IControlMode.html)). Apart from that, the `yarp::dev::IOpenLoopControl` interface and its companion `yarp::dev::IOpenLoopControlRaw` have been removed at robotology/yarp@73c65b2. Affected repositories:

- [x] [kinematics-dynamics](https://github.com/roboticslab-uc3m/kinematics-dynamics) ([2e90f99](https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/2e90f99))
- [x] [openrave-yarp-plugins](https://github.com/roboticslab-uc3m/openrave-yarp-plugins) ([b7ae4ee](https://github.com/roboticslab-uc3m/openrave-yarp-plugins/commit/b7ae4ee), [ba7c632](https://github.com/roboticslab-uc3m/openrave-yarp-plugins/commit/ba7c632))
- [x] [yarp-devices](https://github.com/roboticslab-uc3m/yarp-devices) ([6e0232e](https://github.com/roboticslab-uc3m/yarp-devices/commit/6e0232e))
- ~~[manip-waiter](https://github.com/roboticslab-uc3m/manip-waiter)~~ (see comments)
- [x] [asibot-main](https://github.com/roboticslab-uc3m/asibot-main) ([ec0b387](https://github.com/roboticslab-uc3m/asibot-main/commit/ec0b387), [99471bf](https://github.com/roboticslab-uc3m/asibot-main/commit/99471bf))

**Comment by jgvictores** [comment]
:scream::scream::scream:

**Comment by PeterBowman** [comment]
I'm wondering what happened to `yarp::dev::IPositionDirect::setPositionDirectMode()` at YARP's `devel`. Since there is no `yarp::dev::IControlMode::setPositionDirectMode(int)` counterpart, how are we supposed to set this mode and use the PositionDirect interface?

**Comment by jgvictores** [comment]
Looks like a pretty old issue asking for an `upstream` label, as it apparently never even made it into the [IControlMode.h](https://github.com/robotology/yarp/blob/03bc180cc3a98c7283b6a3a5bf7bc8bf0bc84929/src/libYARP_dev/include/yarp/dev/IControlMode.h) interface of `master`, where there is a [VOCAB_CM_POSITION_DIRECT](https://github.com/robotology/yarp/blob/03bc180cc3a98c7283b6a3a5bf7bc8bf0bc84929/src/libYARP_dev/include/yarp/dev/IControlMode.h#L124) but no actual method.

It would be good for us to recover the method, because it's what we use for the Technosoft IPos driver `PT Mode` (driver's modality where we push motor positions into a buffer).

**Comment by PeterBowman** [comment]
Note to myself: start thinking about dropping *old* `IControlMode` methods in favour of the more generic `IControlMode2::(set|get)ControlMode(s)` with vocabs ([reference](http://www.yarp.it/classyarp_1_1dev_1_1IControlMode2.html)). In fact, this is how we should use now said modes, provided we upgrade our implementations to adopt `IControlMode2`.

**Comment by PeterBowman** [comment]
> Note to myself: start thinking about dropping old IControlMode methods in favour of the more generic IControlMode2::(set|get)ControlMode(s) with vocabs (reference).

Example: roboticslab-uc3m/yarp-devices@3c4e80a.

**Comment by PeterBowman** [comment]
All done but a few deprecated commands used in [manip-waiter/programs/manipWaiterExecManip/InCvPort.cpp](https://github.com/roboticslab-uc3m/manip-waiter/blob/30a5995/programs/manipWaiterExecManip/InCvPort.cpp). I was told not to bother with this (@jgvictores).

**Comment by PeterBowman** [comment]
Confirming that `setPositionMode` et al. will be deprecated soon and eventually removed: robotology/yarp#1223. This is the deployment schedule for the next two releases (per https://github.com/robotology/yarp/projects):

* YARP v2.3.70 (2017/06/15)
* YARP v2.3.72 (2017/10/15)

**Comment by jgvictores** [comment]
Reminder to self: check with @jmgarciah before anything breaks on https://github.com/roboticslab-uc3m/manip-waiter
