### ISSUE TITLE
Upgrade with private repos!

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/QA#19]
We've upgraded @roboticslab-uc3m to an organization plan with unlimited free private repositories and unlimited seats (renewable after 2 years).

@PeterBowman All is set to import https://github.com/jgvictores/amor-api to https://github.com/roboticslab-uc3m :smile:

**Comment by David-Estevez** [comment]
@jgvictores  Can we move also horus & light-dome?

**Comment by jgvictores** [comment]
@David-Estevez That would be great!

**Comment by David-Estevez** [comment]
I'll do that ASAP :+1:

**Comment by PeterBowman** [comment]
Glad to hear that, @jgvictores! Would you mind transferring ownership to our org? I don't have sufficient permissions - no access to the *Settings tab* on amor-api.

**Comment by jgvictores** [comment]
Migrated `amor-api`. :smile:

**Comment by jgvictores** [comment]
@David-Estevez @PeterBowman All OK to close this issue?

**Comment by PeterBowman** [comment]
Ping @David-Estevez.
