### ISSUE TITLE
RoboticsLabUC3M Youtube Channel

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/QA#8]
Alberto Jardón y Carlos me han pedido subir un vídeo que grabamos ayer de la demo waiter al canal de RoboticsLabUC3M. ¿Podrías @jgvictores facilitarme usuario y contraseña?
Gracias!!!

**Comment by jgvictores** [comment]
Yo sólo tengo de mi canal... Eso me parece que lo lleva Edu.

**Comment by jgvictores** [comment]
...y la cámara buena, Santi!

**Comment by jgvictores** [comment]
@rsantos88 ¿Todo OK respecto a esto?

**Comment by rsantos88** [comment]
@jgvictores Si! ya tenemos el [video](https://www.youtube.com/watch?v=mZ-5I0wXxmY) subido al canal.
Cierro issue.

**Comment by jgvictores** [comment]
Canales de interés:
- https://www.youtube.com/user/RoboticsLabUC3M
- https://www.youtube.com/user/jgvictores
- http://www.dailymotion.com/santimorante

**Comment by PeterBowman** [comment]
> Canales de interés:

\+ https://www.youtube.com/channel/UCpi9pRtQPsNPPseycu-tpJQ (Robótica Asistencial UC3M)
